repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.1.1
    hooks:
      - id: sqlfluff-lint
        additional_dependencies:
          [dbt-snowflake==1.8.3, sqlfluff-templater-dbt==3.1.1]
      - id: sqlfluff-fix
        stages: [manual]
        additional_dependencies:
          [dbt-snowflake==1.8.3, sqlfluff-templater-dbt==3.1.1]
